/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 6137623b1a642dd18c19eadf5ef1bc9d)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	ASSETS: Fetcher;
	CF_ACCESS_AUD: "1f3c1c9fce8e8354f1f095c0afdd6856b60b1beade0f320c16bf65e5e897a891";
	CF_ACCESS_TEAM_DOMAIN: "https://icy-silence-7f17.cloudflareaccess.com";
	INVENTORY_ADMIN_EMAIL: "gerpxd@gmail.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CF_ACCESS_AUD" | "CF_ACCESS_TEAM_DOMAIN" | "INVENTORY_ADMIN_EMAIL">> {}
}
