/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: d42f08afd7a87cacac10b50c17b8dfd9)
interface __BaseEnv_CloudflareEnv {
	DEVICE_IMAGES: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	INVENTORY_WRITE_ACCESS_MINUTES: "30";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "INVENTORY_WRITE_ACCESS_MINUTES">> {}
}
